### ISSUE TITLE
Importing cidr-tools causes an error

### ISSUE THREAD

**Issue by akm0sk1t** [silverwind/cidr-tools#20]
The error happens when I'm trying `import { parse } from 'cidr-tools'` as described in the documentation

```
server  | /app/dist/modules/networks/cidr-range-detection.service.js:17
server  | const cidr_tools_1 = require("cidr-tools");
server  |                      ^
server  | Error [ERR_REQUIRE_ESM]: require() of ES Module /app/node_modules/cidr-tools/index.js from /app/dist/modules/networks/cidr-range-detection.service.js not supported.
server  | Instead change the require of index.js in /app/dist/modules/networks/cidr-range-detection.service.js to a dynamic import() which is available in all CommonJS modules.
server  |     at Object.<anonymous> (/app/dist/modules/networks/cidr-range-detection.service.js:17:22)
server  |     at Object.<anonymous> (/app/dist/modules/networks/networks.module.js:51:48)
server  |     at Object.<anonymous> (/app/dist/app.module.js:39:28)
server  |     at Object.<anonymous> (/app/dist/main.js:5:22)
```

My `package.json`:

```
{
  "dependencies": {
    "cidr-tools": "7.0.4",
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.6.1",
    "@typescript-eslint/parser": "^4.6.1",
    "eslint": "^7.12.1",
    "eslint-config-prettier": "^6.15.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-prettier": "^3.1.4",
    "prettier": "^2.1.2",
    "ts-loader": "^8.0.8",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "4.7.4"
  },
    "setupFiles": [
      "./setupTests.ts"
    ],
    "modulePaths": [
      "<rootDir>/../"
    ]
  },
  "engines": {
    "node": ">=16.20.2",
    "npm": ">=8.19.4"
  }
}

```

**Comment by silverwind** [comment]
Your package is CommonJS and therefore can not import ESM modules like `cidr-tools`. You need to switch your project to ESM, see https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c for some pointers.
